### PR TITLE
Support attr.val being boolean

### PR DESCRIPTION
**Pull request by TimothyGu**

### CODE REVIEW

**Comment by alubbe** [comment]
LGTM

**Comment by hemanth** [comment]
Any related issue?

**Comment by TimothyGu** [comment]
@alubbe, thanks for checking. @hemanth, no, the assert is placed pretty recently and this module isn't used by anyone.

**Comment by hemanth** [comment]
:+1:

**Comment by TimothyGu** [comment]
@ForbesLindesay, I'd love it if you could publish the current master as 1.0.2 (I've already tagged it) or add me as an owner. Thanks!

**Pull request merged**
